# source: https://github.com/lookback/s3-copy-action
name: Upload dags to S3

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push build to S3
        uses: sai-sharan/aws-s3-sync-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID}}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: 'us-east-1'
          source: 'dags'
          destination_bucket: ${{ secrets.AWS_S3_BUCKET }}
          destination_prefix: ${{ secrets.AWS_S3_DESTINATION_PREFIX }}
          delete: true
          quiet: false